services:
  - type: web
    name: telegram-student-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      # حط توكن التليجرام هنا - من @BotFather
      - key: BOT_TOKEN
        value: "8027180784:AAGM6R_IbRNDQQu5WsJr0YPfTj-Lk6IwHDc"
        sync: true
      
      # حط مفتاح Groq API هنا - من console.groq.com
      - key: GROQ_API_KEY
        value: "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"
        sync: true
      
      # إصدار Python
      - key: PYTHON_VERSION
        value: 3.11.0
        
